//
// Copyright (c) 2025-present, Trail of Bits, Inc.
// All rights reserved.
//
// This source code is licensed in accordance with the terms specified in
// the LICENSE file found in the root directory of this source tree.
//

use std::{
    collections::HashMap,
    ffi::{CStr, CString},
    os,
};

use crate::{ColumnType, ColumnValue, Error, ErrorKind, Result, Row, RowList, TablePlugin};

use crate::sqlite::{
    self, sqlite3, sqlite3_close, sqlite3_create_module, sqlite3_module, sqlite3_open,
    sqlite3_vtab, SQLITE_DONE, SQLITE_ERROR, SQLITE_OK, SQLITE_ROW,
};

/// This struct is used to wrap the table plugin before it is passed to sqlite
/// Wrapping the trait object ensures we don't lose the vtable when passing this
/// through the ffi
struct TablePluginWrapper<'a> {
    /// The table plugin
    table_plugin: &'a dyn TablePlugin,
}

/// Query data, as returned by Database::query
#[derive(Debug)]
pub struct QueryData {
    /// The column names in the order they appear in the SQL query
    pub column_order: Vec<String>,

    /// The list of rows generated by sqlite
    pub row_list: RowList,
}

/// A wrapper around the sqlite3 database
pub struct Database<'a> {
    /// The sqlite3 database
    sqlite: *mut sqlite3,

    /// A map of table names to registered table plugins
    table_plugin_map: HashMap<String, Box<TablePluginWrapper<'a>>>,
}

/// The database implementation
impl<'a> Database<'a> {
    /// Creates a new in-memory database
    pub fn new() -> Result<Self> {
        let mut sqlite: *mut sqlite3 = std::ptr::null_mut();
        let memory_database_name = CString::new(":memory:").map_err(|_| {
            Error::new(
                ErrorKind::InternalError,
                "Failed to allocate the :memory: database name",
            )
        })?;

        if unsafe { sqlite3_open(memory_database_name.as_ptr(), &mut sqlite) as u32 } != SQLITE_OK {
            return Err(Error::new(
                ErrorKind::DatabaseCreationFailed,
                "Failed to create the database",
            ));
        }

        Ok(Self {
            sqlite,
            table_plugin_map: HashMap::new(),
        })
    }

    /// Executes a query and returns the result
    pub fn query(&self, query: &str) -> Result<QueryData> {
        let mut stmt: *mut sqlite::sqlite3_stmt = std::ptr::null_mut();

        let query_string = CString::new(query).map_err(|_| {
            Error::new(
                ErrorKind::InternalError,
                "Failed to allocate the query string",
            )
        })?;

        let query_string_size = query_string.as_bytes().len() as i32;

        let error = unsafe {
            sqlite::sqlite3_prepare_v2(
                self.sqlite,
                query_string.as_ptr(),
                query_string_size,
                &mut stmt,
                std::ptr::null_mut(),
            )
        } as u32;

        if error != SQLITE_OK {
            let error_message = unsafe {
                let buffer = sqlite::sqlite3_errmsg(self.sqlite);
                CStr::from_ptr(buffer).to_string_lossy().into_owned()
            };

            return Err(Error::new(
                ErrorKind::InvalidSqlStatement,
                &format!("The sqlite library returned error {} when trying to compile the following SQL statement: {}. Error message: {}", error, query, error_message),
            ));
        }

        let column_count = unsafe { sqlite::sqlite3_column_count(stmt) } as usize;
        let mut query_data = QueryData {
            column_order: Vec::new(),
            row_list: RowList::new(),
        };

        loop {
            let error = unsafe { sqlite::sqlite3_step(stmt) } as u32;
            if error == SQLITE_DONE {
                break;
            } else if error != SQLITE_ROW {
                let error_message = unsafe {
                    let buffer = sqlite::sqlite3_errmsg(self.sqlite);
                    CStr::from_ptr(buffer).to_string_lossy().into_owned()
                };

                return Err(Error::new(
                    ErrorKind::TablePluginError,
                    &format!(
                        "The table plugin has failed to generate the next row. Error message: {}",
                        error_message
                    ),
                ));
            }

            let mut current_row = Row::new();
            for column_index in 0..column_count {
                let column_name_cstr =
                    unsafe { sqlite::sqlite3_column_name(stmt, column_index as i32) };

                let column_name =
                    String::from_utf8_lossy(unsafe { CStr::from_ptr(column_name_cstr).to_bytes() })
                        .to_string();

                if query_data.column_order.len() != column_count {
                    query_data.column_order.push(column_name.clone());
                }

                let column_type =
                    unsafe { sqlite::sqlite3_column_type(stmt, column_index as i32) } as u32;

                let column_value = match column_type {
                    sqlite::SQLITE_INTEGER => {
                        let value =
                            unsafe { sqlite::sqlite3_column_int64(stmt, column_index as i32) };

                        Some(ColumnValue::SignedInteger(value))
                    }

                    sqlite::SQLITE_FLOAT => {
                        let value =
                            unsafe { sqlite::sqlite3_column_double(stmt, column_index as i32) };

                        Some(ColumnValue::Double(value))
                    }

                    sqlite::SQLITE_TEXT => {
                        let value = unsafe {
                            sqlite::sqlite3_column_text(stmt, column_index as i32) as *const i8
                        };

                        let value = unsafe { CStr::from_ptr(value).to_bytes() };
                        let value = String::from_utf8_lossy(value).to_string();

                        Some(ColumnValue::String(value))
                    }

                    sqlite::SQLITE_NULL => None,

                    _ => {
                        return Err(Error::new(
                            ErrorKind::TablePluginError,
                            "The table plugin has generated an invalid column type",
                        ));
                    }
                };

                current_row.insert(column_name, column_value);
            }

            query_data.row_list.push(current_row);
        }

        unsafe {
            sqlite::sqlite3_finalize(stmt);
        }

        Ok(query_data)
    }

    /// Registers a new table plugin
    pub fn register_table_plugin(&mut self, table_plugin: &'a dyn TablePlugin) -> Result<()> {
        if self.table_plugin_map.contains_key(&table_plugin.name()) {
            return Err(Error::new(
                ErrorKind::DuplicatedTableName,
                &format!("The table {} is already registered", table_plugin.name()),
            ));
        }

        let table_name = CString::new(table_plugin.name()).map_err(|_| {
            Error::new(
                ErrorKind::InvalidTablePluginName,
                "The table plugin name is not valid",
            )
        })?;

        let mut table_plugin_wrapper = Box::new(TablePluginWrapper { table_plugin });
        let table_plugin_wrapper_ptr =
            table_plugin_wrapper.as_mut() as *mut TablePluginWrapper as *mut os::raw::c_void;

        if unsafe {
            sqlite3_create_module(
                self.sqlite,
                table_name.as_ptr(),
                &SQLITE_TABLE_MODULE,
                table_plugin_wrapper_ptr,
            ) as u32
        } != SQLITE_OK
        {
            return Err(Error::new(
                ErrorKind::TablePluginRegistrationError,
                &format!(
                    "The table plugin {} could not be registered",
                    table_plugin.name()
                ),
            ));
        }

        self.table_plugin_map
            .insert(table_plugin.name(), table_plugin_wrapper);

        Ok(())
    }
}

/// Closes the database when it goes out of scope
impl Drop for Database<'_> {
    /// Closes the sqlite3 database
    fn drop(&mut self) {
        unsafe {
            sqlite3_close(self.sqlite);
        }
    }
}

/// A wrapper around the sqlite3 virtual table structure
#[repr(C)]
struct VirtualTable<'a> {
    /// The sqlite3 virtual table structure
    sqlite_vtab: sqlite3_vtab,

    /// A reference to the table plugin
    table_plugin_ref: &'a dyn TablePlugin,
}

/// Returns the sqlite column type
fn get_sqlite_column_type(column_type: &ColumnType) -> &str {
    match column_type {
        ColumnType::SignedInteger => "INTEGER",
        ColumnType::String => "TEXT",
        ColumnType::Double => "REAL",
    }
}

/// Generates the CREATE TABLE statement for the table plugin
fn generate_create_table_statement(table_plugin: &dyn TablePlugin) -> Result<CString> {
    let mut column_declarations = String::new();

    for (column_name, column_type) in table_plugin.schema() {
        if !column_declarations.is_empty() {
            column_declarations.push_str(", ");
        }

        column_declarations.push_str(&format!(
            "{} {}",
            column_name,
            get_sqlite_column_type(&column_type)
        ));
    }

    CString::new(format!(
        "CREATE TABLE {} ({})",
        table_plugin.name(),
        column_declarations
    ))
    .map_err(|_| {
        Error::new(
            ErrorKind::InternalError,
            "Failed to allocate the string for the CREATE TABLE statemenet",
        )
    })
}

/// This is the callback invoked by sqlite to create the virtual table
#[allow(non_snake_case, non_camel_case_types)]
unsafe extern "C" fn sqlite_connect_callback(
    arg1: *mut sqlite::sqlite3,
    pAux: *mut os::raw::c_void,
    _argc: os::raw::c_int,
    _argv: *const *const os::raw::c_char,
    ppVTab: *mut *mut sqlite::sqlite3_vtab,
    _arg2: *mut *mut os::raw::c_char,
) -> os::raw::c_int {
    let table_plugin_wrapper = &*(pAux as *const TablePluginWrapper);
    let table_plugin = table_plugin_wrapper.table_plugin;

    let raw_vtab = Box::into_raw(Box::new(VirtualTable {
        sqlite_vtab: sqlite3_vtab {
            pModule: std::ptr::null(),
            nRef: 0,
            zErrMsg: std::ptr::null_mut(),
        },

        table_plugin_ref: table_plugin_wrapper.table_plugin,
    }));

    let create_table_statement = generate_create_table_statement(table_plugin)
        .expect("Failed to generate the CREATE TABLE statement");

    sqlite::sqlite3_declare_vtab(arg1, create_table_statement.as_ptr());

    *ppVTab = raw_vtab as *mut sqlite3_vtab;
    SQLITE_OK as os::raw::c_int
}

/// Unused
#[allow(non_snake_case, non_camel_case_types)]
unsafe extern "C" fn sqlite_xbest_index_callback(
    _pVTab: *mut sqlite3_vtab,
    _arg1: *mut sqlite::sqlite3_index_info,
) -> os::raw::c_int {
    SQLITE_OK as os::raw::c_int
}

/// Destroys the virtual table
#[allow(non_snake_case, non_camel_case_types)]
unsafe extern "C" fn sqlite_disconnect_callback(
    pVTab: *mut sqlite::sqlite3_vtab,
) -> os::raw::c_int {
    drop(Box::from_raw(pVTab as *mut VirtualTable));
    SQLITE_OK as os::raw::c_int
}

/// A wrapper around the sqlite3 virtual table cursor structure
#[repr(C)]
struct VirtualTableCursor {
    /// The sqlite3 virtual table cursor structure
    sqlite_vtab_cursor: sqlite::sqlite3_vtab_cursor,

    /// The list of rows generated by the table plugin
    row_list: RowList,

    /// The current row index
    current_row: usize,
}

/// This is the callback invoked by sqlite to create new cursors
#[allow(non_snake_case, non_camel_case_types)]
unsafe extern "C" fn sqlite_open_callback(
    pVTab: *mut sqlite::sqlite3_vtab,
    ppCursor: *mut *mut sqlite::sqlite3_vtab_cursor,
) -> os::raw::c_int {
    let table_cursor = Box::new(VirtualTableCursor {
        sqlite_vtab_cursor: sqlite::sqlite3_vtab_cursor { pVtab: pVTab },
        row_list: RowList::new(),
        current_row: 0,
    });

    *ppCursor = Box::into_raw(table_cursor) as *mut sqlite::sqlite3_vtab_cursor;
    SQLITE_OK as os::raw::c_int
}

/// This is the callback invoked by sqlite to destroy cursors
#[allow(non_snake_case, non_camel_case_types)]
unsafe extern "C" fn sqlite_close_callback(
    arg1: *mut sqlite::sqlite3_vtab_cursor,
) -> os::raw::c_int {
    drop(Box::from_raw(arg1 as *mut VirtualTableCursor));
    SQLITE_OK as os::raw::c_int
}

/// Sets the error message in the sqlite3 virtual table structure
fn set_vtab_error_message(sqlite_vtab: &mut sqlite3_vtab, message: String) {
    if !sqlite_vtab.zErrMsg.is_null() {
        unsafe { sqlite::sqlite3_free(sqlite_vtab.zErrMsg as *mut std::ffi::c_void) };
        sqlite_vtab.zErrMsg = std::ptr::null_mut();
    }

    let cstring_message = match CString::new(message) {
        Ok(cstring_message) => cstring_message,

        Err(_) => CString::new(String::from(
            "The table plugin has generated an invalid error message",
        ))
        .unwrap(),
    };

    let cstring_message_ptr = cstring_message.as_ptr() as *mut i8;
    let cstring_message_len = cstring_message.as_bytes().len() as i32;

    let error_message_buffer = unsafe {
        let error_message_buffer = sqlite::sqlite3_malloc(cstring_message_len + 1) as *mut i8;

        std::ptr::copy_nonoverlapping(
            cstring_message_ptr,
            error_message_buffer,
            cstring_message_len as usize,
        );

        error_message_buffer
    };

    sqlite_vtab.zErrMsg = error_message_buffer;
}

/// This is where the table plugin is invoked to generate the rows
#[allow(non_snake_case, non_camel_case_types)]
unsafe extern "C" fn sqlite_xfilter_callback(
    arg1: *mut sqlite::sqlite3_vtab_cursor,
    _idxNum: os::raw::c_int,
    _idxStr: *const os::raw::c_char,
    _argc: os::raw::c_int,
    _argv: *mut *mut sqlite::sqlite3_value,
) -> os::raw::c_int {
    let virtual_table = &mut *((*arg1).pVtab as *mut VirtualTable);
    let table_plugin = &virtual_table.table_plugin_ref;

    let table_cursor = &mut *(arg1 as *mut VirtualTableCursor);
    table_cursor.current_row = 0;
    table_cursor.row_list = match table_plugin.generate() {
        Err(error) => {
            set_vtab_error_message(&mut virtual_table.sqlite_vtab, format!("{:?}", error));
            return SQLITE_ERROR as os::raw::c_int;
        }

        Ok(row_list) => row_list,
    };

    SQLITE_OK as os::raw::c_int
}

/// This is the callback invoked by sqlite to advance the cursor
#[allow(non_snake_case, non_camel_case_types)]
unsafe extern "C" fn sqlite_xnext_callback(
    arg1: *mut sqlite::sqlite3_vtab_cursor,
) -> os::raw::c_int {
    let table_cursor = &mut *(arg1 as *mut VirtualTableCursor);
    table_cursor.current_row += 1;

    SQLITE_OK as os::raw::c_int
}

/// This is the callback invoked by sqlite to check if the cursor has reached the end of the generated rows
#[allow(non_snake_case, non_camel_case_types)]
unsafe extern "C" fn sqlite_xeof_callback(
    arg1: *mut sqlite::sqlite3_vtab_cursor,
) -> os::raw::c_int {
    let table_cursor = &mut *(arg1 as *mut VirtualTableCursor);
    if table_cursor.current_row >= table_cursor.row_list.len() {
        1
    } else {
        0
    }
}

/// This is the callback invoked by sqlite to release CString objects returned by the xColumn callback
unsafe extern "C" fn release_cstring(cstring: *mut ::std::os::raw::c_void) {
    drop(CString::from_raw(cstring as *mut _));
}

/// This is the callback invoked by sqlite to retrieve the column value
#[allow(non_snake_case, non_camel_case_types)]
unsafe extern "C" fn sqlite_xcolumn_callback(
    arg1: *mut sqlite::sqlite3_vtab_cursor,
    arg2: *mut sqlite::sqlite3_context,
    arg3: os::raw::c_int,
) -> os::raw::c_int {
    let table_cursor = &mut *(arg1 as *mut VirtualTableCursor);
    if table_cursor.current_row >= table_cursor.row_list.len() {
        return SQLITE_ERROR as os::raw::c_int;
    }

    let current_row = match table_cursor.row_list.get(table_cursor.current_row) {
        Some(row) => row,
        None => return SQLITE_ERROR as os::raw::c_int,
    };

    let column_number = arg3 as usize;
    if column_number >= current_row.len() {
        return SQLITE_ERROR as os::raw::c_int;
    }

    let current_column = match current_row.iter().nth(column_number) {
        Some(column) => column,
        None => return SQLITE_ERROR as os::raw::c_int,
    };

    match &current_column.1 {
        None => {
            sqlite::sqlite3_result_null(arg2);
        }

        Some(value) => {
            match value {
                ColumnValue::Double(value) => {
                    sqlite::sqlite3_result_double(arg2, *value);
                }

                ColumnValue::SignedInteger(value) => {
                    sqlite::sqlite3_result_int64(arg2, *value);
                }

                ColumnValue::String(value) => {
                    let c_string = match CString::new(&value[..]) {
                        Ok(c_string) => c_string.into_raw(),
                        Err(error) => {
                            let virtual_table =
                                &mut *(table_cursor.sqlite_vtab_cursor.pVtab as *mut VirtualTable);

                            set_vtab_error_message(&mut virtual_table.sqlite_vtab, format!("The table plugin has generated an invalid text column value. {:?}", error));
                            return SQLITE_ERROR as os::raw::c_int;
                        }
                    };

                    sqlite::sqlite3_result_text(
                        arg2,
                        c_string,
                        value.len() as i32,
                        Some(release_cstring),
                    );
                }
            }
        }
    };

    SQLITE_OK as os::raw::c_int
}

/// This is the callback invoked by sqlite to retrieve the rowid
#[allow(non_snake_case, non_camel_case_types)]
unsafe extern "C" fn sqlite_xrowid_callback(
    arg1: *mut sqlite::sqlite3_vtab_cursor,
    pRowid: *mut sqlite::sqlite3_int64,
) -> os::raw::c_int {
    let table_cursor = &mut *(arg1 as *mut VirtualTableCursor);
    *pRowid = (table_cursor.current_row + 1) as sqlite::sqlite3_int64;

    SQLITE_OK as os::raw::c_int
}

/// The sqlite3 module that is passed to sqlite3_create_module
const SQLITE_TABLE_MODULE: sqlite3_module = sqlite3_module {
    iVersion: 3,
    xCreate: Some(sqlite_connect_callback),
    xConnect: Some(sqlite_connect_callback),
    xBestIndex: Some(sqlite_xbest_index_callback),
    xDisconnect: Some(sqlite_disconnect_callback),
    xDestroy: Some(sqlite_disconnect_callback),
    xOpen: Some(sqlite_open_callback),
    xClose: Some(sqlite_close_callback),
    xFilter: Some(sqlite_xfilter_callback),
    xNext: Some(sqlite_xnext_callback),
    xEof: Some(sqlite_xeof_callback),
    xColumn: Some(sqlite_xcolumn_callback),
    xRowid: Some(sqlite_xrowid_callback),
    xUpdate: None,
    xBegin: None,
    xSync: None,
    xCommit: None,
    xRollback: None,
    xFindFunction: None,
    xRename: None,
    xSavepoint: None,
    xRelease: None,
    xRollbackTo: None,
    xShadowName: None,
    xIntegrity: None,
};

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    struct TestTablePlugin {
        return_error: bool,
    }

    impl TestTablePlugin {
        fn new(return_error: bool) -> Self {
            Self { return_error }
        }
    }

    impl TablePlugin for TestTablePlugin {
        fn schema(&self) -> BTreeMap<String, ColumnType> {
            let mut schema = BTreeMap::new();
            schema.insert("column1".to_owned(), ColumnType::SignedInteger);
            schema.insert("column2".to_owned(), ColumnType::String);
            schema.insert("column3".to_owned(), ColumnType::Double);

            schema
        }

        fn name(&self) -> String {
            "test_table".to_owned()
        }

        fn generate(&self) -> Result<RowList> {
            if self.return_error {
                return Err(Error::new(
                    ErrorKind::TablePluginError,
                    "Custom error message",
                ));
            }

            let mut row = Row::new();
            row.insert(String::from("column1"), Some(ColumnValue::SignedInteger(1)));
            row.insert(
                String::from("column2"),
                Some(ColumnValue::String(String::from("Test String"))),
            );

            row.insert(
                String::from("column3"),
                Some(ColumnValue::Double(std::f64::consts::PI)),
            );

            Ok(vec![row])
        }
    }

    #[test]
    fn test_get_sqlite_column_type() {
        assert_eq!(
            get_sqlite_column_type(&ColumnType::SignedInteger),
            "INTEGER"
        );
        assert_eq!(get_sqlite_column_type(&ColumnType::String), "TEXT");
        assert_eq!(get_sqlite_column_type(&ColumnType::Double), "REAL");
    }

    #[test]
    fn test_generate_create_table_statement() {
        let table_plugin = TestTablePlugin::new(false);
        let create_table_statement = generate_create_table_statement(&table_plugin).unwrap();
        let create_table_statement = create_table_statement.to_string_lossy();

        assert_eq!(
            create_table_statement,
            "CREATE TABLE test_table (column1 INTEGER, column2 TEXT, column3 REAL)"
        );
    }

    #[test]
    fn test_table_registration() {
        let table_plugin = TestTablePlugin::new(false);

        let mut database = Database::new().unwrap();
        let error = database.query("SELECT * FROM test_table").unwrap_err();
        assert_eq!(*error.kind(), ErrorKind::InvalidSqlStatement);

        database
            .register_table_plugin(&table_plugin)
            .expect("Failed to register the table plugin");

        let query_data = database
            .query("SELECT * FROM test_table")
            .expect("Failed to execute the query");

        assert_eq!(query_data.column_order.len(), 3);
        assert_eq!(query_data.column_order[0], "column1");
        assert_eq!(query_data.column_order[1], "column2");
        assert_eq!(query_data.column_order[2], "column3");

        assert_eq!(query_data.row_list.len(), 1);
        assert_eq!(query_data.row_list[0].len(), 3);

        let column1 = query_data.row_list[0].get("column1").unwrap();
        assert_eq!(column1, &Some(ColumnValue::SignedInteger(1)));

        let column2 = query_data.row_list[0].get("column2").unwrap();
        assert_eq!(
            column2,
            &Some(ColumnValue::String(String::from("Test String")))
        );

        let column3 = query_data.row_list[0].get("column3").unwrap();
        assert_eq!(column3, &Some(ColumnValue::Double(std::f64::consts::PI)));
    }

    #[test]
    fn test_table_generation_error() {
        let table_plugin = TestTablePlugin::new(true);

        let mut database = Database::new().unwrap();
        let error = database.query("SELECT * FROM test_table").unwrap_err();
        assert_eq!(*error.kind(), ErrorKind::InvalidSqlStatement);

        database
            .register_table_plugin(&table_plugin)
            .expect("Failed to register the table plugin");

        let error = database.query("SELECT * FROM test_table").unwrap_err();
        assert_eq!(*error.kind(), ErrorKind::TablePluginError);
        assert!(error.message().contains("Custom error message"));
    }
}
