#
# Copyright (c) 2025-present, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: 'mquire package'
description: 'Build and upload package artifacts'

runs:
  using: 'composite'
  steps:
    - name: Set package name prefix
      id: prefix
      shell: bash
      run: |
        os=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
        arch=$(echo "${{ runner.arch }}" | tr '[:upper:]' '[:lower:]')
        echo "value=${os}-${arch}" >> $GITHUB_OUTPUT

    - name: Build packages
      shell: bash
      run: |
        cmake \
          -S package \
          -B package-build \
          -DMQUIRE_REPOSITORY_PATH="$(pwd)"

        cmake \
          --build package-build \
          --target package

    - name: Upload .deb package
      if: ${{ runner.os == 'Linux' }}
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: ${{ steps.prefix.outputs.value }}-deb
        path: package-build/*.deb

    - name: Upload .rpm package
      if: ${{ runner.os == 'Linux' }}
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: ${{ steps.prefix.outputs.value }}-rpm
        path: package-build/*.rpm

    - name: Upload .tar.gz package
      if: ${{ runner.os != 'Windows' }}
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: ${{ steps.prefix.outputs.value }}-tgz
        path: package-build/*.tar.gz

    - name: Upload .zip package
      if: ${{ runner.os == 'Windows' }}
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      with:
        name: ${{ steps.prefix.outputs.value }}-zip
        path: package-build/*.zip
