#
# Copyright (c) 2025-present, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: 'mquire windows build'
description: 'Build and test mquire on Windows'

inputs:
  build_type:
    description: 'Build type (Debug or Release)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install and update Rust
      shell: bash
      run: rustup update

    - name: Setup the command line build arguments
      id: build_parameter
      shell: bash
      run: |
        if [[ "${{ inputs.build_type }}" == "Release" ]]; then
          echo "VALUE=--release" >> $GITHUB_OUTPUT
        fi

    - name: Build the project
      shell: bash
      run: cargo build ${{ steps.build_parameter.outputs.VALUE }}

    - name: Run the tests
      shell: bash
      run: |
        cargo test \
          --examples \
          ${{ steps.build_parameter.outputs.VALUE }}
