#
# Copyright (c) 2025-present, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: CI

on:
  pull_request:
    branches:
      - '*'

  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    permissions:
      security-events: write
      contents: read

    steps:
      - name: Clone the source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2

  check:
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    permissions:
      contents: read

    steps:
      - name: Clone the source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Run checks
        uses: ./.github/actions/mquire/check

  build:
    needs: [check]
    timeout-minutes: 30

    permissions:
      contents: read

    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            build_type: Release

          - os: ubuntu-24.04
            build_type: Debug

          - os: macos-15
            build_type: Release

          - os: windows-2022
            build_type: Release

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone the source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

        with:
          persist-credentials: false

      - name: Build
        uses: ./.github/actions/mquire/build

        with:
          build_type: ${{ matrix.build_type }}

      - name: Build and upload packages
        if: ${{ matrix.build_type == 'Release' }}
        uses: ./.github/actions/mquire/package

  sql-queries:
    needs: [check, build]

    permissions:
      contents: read

    uses: ./.github/workflows/integration_sql-queries_main.yml

    secrets:
      MQUIRE_TEST_S3_BUCKET: ${{ secrets.MQUIRE_TEST_S3_BUCKET }}
      MQUIRE_TEST_S3_ENDPOINT: ${{ secrets.MQUIRE_TEST_S3_ENDPOINT }}
      MQUIRE_TEST_AWS_ACCESS_KEY_ID: ${{ secrets.MQUIRE_TEST_AWS_ACCESS_KEY_ID }}
      MQUIRE_TEST_AWS_SECRET_ACCESS_KEY: ${{ secrets.MQUIRE_TEST_AWS_SECRET_ACCESS_KEY }}
