#
# Copyright (c) 2025-present, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: CI

on:
  pull_request:
    branches:
      - '*'

  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  rust_check:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Clone the source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run Rust checks
        uses: ./.github/actions/mquire/check
        with:
          build_type: Debug

  verifier_check:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Clone the source code
        uses: actions/checkout@v6

      - name: Run verifier checks
        uses: ./.github/actions/mquire-sql-query-verifier/check

  linux:
    needs: [rust_check]
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    strategy:
      matrix:
        build_type: [Release, Debug]

    steps:
      - name: Clone the source code
        uses: actions/checkout@v6

      - name: Build and test
        uses: ./.github/actions/mquire/posix-build
        with:
          build_type: ${{ matrix.build_type }}
          runner_os: Linux

      - name: Find and upload the .deb Linux package
        if: ${{ matrix.build_type == 'Release' }}
        uses: actions/upload-artifact@v6
        with:
          name: linux-deb-package
          path: package-build/*.deb

      - name: Find and upload the .rpm Linux package
        if: ${{ matrix.build_type == 'Release' }}
        uses: actions/upload-artifact@v6
        with:
          name: linux-rpm-package
          path: package-build/*.rpm

      - name: Find and upload the .tar.gz Linux package
        if: ${{ matrix.build_type == 'Release' }}
        uses: actions/upload-artifact@v6
        with:
          name: linux-tgz-package
          path: package-build/*.tar.gz

  macos:
    needs: [rust_check]
    runs-on: macos-15
    timeout-minutes: 30

    steps:
      - name: Clone the source code
        uses: actions/checkout@v6

      - name: Build and test
        uses: ./.github/actions/mquire/posix-build
        with:
          build_type: Release
          runner_os: macOS

  windows:
    needs: [rust_check]
    runs-on: windows-2022
    timeout-minutes: 30

    steps:
      - name: Clone the source code
        uses: actions/checkout@v6

      - name: Build and test
        uses: ./.github/actions/mquire/windows-build
        with:
          build_type: Release

  sql-queries:
    needs: [rust_check, verifier_check, linux, macos, windows]
    uses: ./.github/workflows/integration_sql-queries_main.yml
    secrets: inherit
