#
# Copyright (c) 2025-present, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: posix_check

on:
  workflow_call:
    inputs:
      runner_image:
        required: true
        type: string

      build_type:
        required: true
        type: string

jobs:
  posix_check:
    runs-on: ${{ inputs.runner_image }}

    steps:
      - name: Clone the source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Update Rust
        run: |
          rustup update

      - name: Setup the command line build arguments
        id: build_type
        run: |
          if [[ "${{ inputs.build_type }}" == "Release" ]]; then
            echo "VALUE=--release" >> $GITHUB_OUTPUT
          fi

      - name: Run cargo fmt
        run: |
          cargo fmt --all --check

      - name: Run cargo clippy
        run: |
          cargo clippy \
            ${{ steps.build_type.outputs.VALUE }} \
            --all-targets \
            --all-features \
            --examples \
            -- -D warnings

      - name: Run cargo check
        run: |
          cargo check \
            ${{ steps.build_type.outputs.VALUE }} \
            --all-targets \
            --all-features \
            --examples \
            --tests \
            --workspace
