#
# Copyright (c) 2025-present, Trail of Bits, Inc.
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: posix_build

on:
  workflow_call:
    inputs:
      runner_image:
        required: true
        type: string

      build_type:
        required: true
        type: string

jobs:
  posix_build:
    runs-on: ${{ inputs.runner_image }}

    steps:
      - name: Clone the source code
        uses: actions/checkout@v4

      - name: Install and update Rust
        run: |
          rustup update

          if [[ "${{ inputs.runner_image }}" == "ubuntu"* ]]; then
            sudo apt-get update
            sudo apt-get install -y \
              musl-tools

            rustup target add x86_64-unknown-linux-musl
          fi

      - name: Select the Rust target
        id: target_parameter
        run: |
          if [[ "${{ inputs.runner_image }}" == "ubuntu"* ]]; then
            echo "VALUE=--target x86_64-unknown-linux-musl" >> $GITHUB_OUTPUT
          fi

      - name: Setup the command line build arguments
        id: build_parameter
        run: |
          if [[ "${{ inputs.build_type }}" == "Release" ]]; then
            echo "VALUE=--release" >> $GITHUB_OUTPUT
          fi

      - name: Build the project
        run: |
          cargo build \
            ${{ steps.target_parameter.outputs.VALUE }} \
            ${{ steps.build_parameter.outputs.VALUE }}

      - name: Run the tests
        run: |
          cargo test \
            --examples \
            ${{ steps.target_parameter.outputs.VALUE }} \
            ${{ steps.build_parameter.outputs.VALUE }}

      - name: Build the packages
        if: ${{ runner.os == 'Linux' && inputs.build_type == 'Release' }}
        run: |
          find target -type f | sort -u

          cmake \
            -S package \
            -B package-build \
            -DMQUIRE_REPOSITORY_PATH="$(pwd)"

          cmake \
            --build package-build \
            --target package

          find package-build -type f | sort -u

      - name: Find and upload the .deb Linux package
        if: ${{ runner.os == 'Linux' && inputs.build_type == 'Release' }}
        uses: actions/upload-artifact@v5
        with:
          name: linux-deb-package
          path: package-build/*.deb

      - name: Find and upload the .rpm Linux package
        if: ${{ runner.os == 'Linux' && inputs.build_type == 'Release' }}
        uses: actions/upload-artifact@v5
        with:
          name: linux-rpm-package
          path: package-build/*.rpm

      - name: Find and upload the .tar.gz Linux package
        if: ${{ runner.os == 'Linux' && inputs.build_type == 'Release' }}
        uses: actions/upload-artifact@v5
        with:
          name: linux-tgz-package
          path: package-build/*.tar.gz
